smtp_on: true
smtp_host: smtp.office365.com
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: tls
smtp_username: wrdctest@welkgroup.com
smtp_password: W3lcome!
smtp_from: wrdctest@welkgroup.com
smtp_fromname: ''
smtp_client_hostname: welkgroup.com
smtp_client_helo: ''
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: true
prev_mail_system: php_mail
_core:
  default_config_hash: WEa5Ex_IeAcm6Bm0hmQ4vU_nDwJDB8hW-vxT1qpGIbM
