okta_ajax.settings:
  type: config_object
  label: 'Okta AJAX API settings'
  mapping:
    okta_api_key:
      type: string
      label: 'API Token'
    okta_client_id:
      type: string
      label: 'OpenID Client ID'
    okta_client_secret:
      type: string
      label: 'OpenID Client Secret'
    organisation_url:
      type: string
      label: 'Your Okta organisation'
    okta_domain:
      type: string
      label: 'Your Okta domain'
    default_group_id:
      type: string
      label: 'Default group ID'
    preview_domain:
      type: boolean
      label: 'Use Okta preview domain (overrides Okta domain above)'
