crazyegg.settings:
  type: mapping
  label: 'Settings'
  mapping:
    crazyegg_enabled:
      type: integer
    crazyegg_account_id:
      type: text
    crazyegg_js_scope:
      type: text
    crazyegg_paths:
      type: texts
    crazyegg_roles_excluded:
      type: sequence
      sequence:
        type: number
